update_items:
  - news
social:
    - name: E-mail
      url: mailto:zy_pan@zju.edu.cn
    - name: Github
      url: https://github.com/pan2013e
    - name: Google Scholar
      url: https://scholar.google.com/citations?user=oCyJ8lMAAAAJ
    - name: CV
      url: /assets/CV.pdf
    - name: Albums
      url: /photography
analytics:
  gtag: G-79DB9R2CZC
assets_version: 20260203
info:
  education:
    - institution: National University of Singapore
      sub_institution: Trustworthy and Secure Software (TSS) Group
      degree: Research Associate
      duration: September 2025 - September 2026
      misc:
        - 'Advisor: <a href="https://abhikrc.com">Abhik Roychoudhury</a>'
    - institution: Zhejiang University
      sub_institution: The State Key Laboratory of Blockchain and Data Security
      degree: PhD in Computer Science and Technology
      duration: September 2023 - Present
      misc:
        - 'Supervisor: <a href="https://person.zju.edu.cn/en/xiaohu">Xiaohu Yang</a>, <a href="https://xing-hu.github.io">Xing Hu</a>'
        - 'Advisor: <a href="https://xin-xia.github.io">Xin Xia</a>'
    - institution: Zhejiang University
      sub_institution: Chu Kochen Honors College
      degree: B. Eng. in Computer Science and Technology
      duration: September 2019 - June 2023
  awards:
    - name: National Scholarship
      year: 2024
      committee: Ministry of Education, P.R.C.
    - name: Outstanding Graduate
      year: 2023
      committee: Zhejiang University
avatar_rotator:
  enabled: true
  images:
    - src: /assets/avatars/1.jpg
      caption: "Ottawa, ON, Canada"
    - src: /assets/avatars/2.jpg
      caption: "Cairo, Egypt"
    - src: /assets/avatars/3.jpg
      caption: "East Java, Indonesia"
    - src: /assets/avatars/4.jpg
      caption: "Vancouver, Canada"
    - src: /assets/avatars/5.jpg
      caption: "Harbin, China"
    - src: /assets/avatars/6.jpg
      caption: "Kuala Lumpur, M'sia"
    - src: /assets/avatars/7.jpg
      caption: "Xinjiang, China"
    - src: /assets/avatars/8.jpg
      caption: "Lisbon, Portugal"